### PR TITLE
allreduce_new: Allocate all results and incoming buffers on device memory

### PR DESCRIPTION
**Pull request by shamoya**

### CODE REVIEW

**Comment by yanivbl6** [comment]
Sorry, I only now got to this and it too late for integration. (The memory management [was remodeled](https://github.com/yanivbl6/gloo/blob/yaniv_branch/gloo/mlx5dv_mem.h#L78))
I can use your code and implement it (I am assuming you are too busy for this).

**Comment by shamoya** [comment]
I can do it if you want, since it's fun.
Tell me what u prefer ...

**Comment by yanivbl6** [comment]
Great, I prefer that you integrate it. Tell me if you have any questions.

In short, you need to make a class "Memic" that inherits from NetMem, similar to HostMem but using memic instead of malloc+reg_mr. Then we just need to update the pipelined memory constructor to support your new class- and the rest is already integrated.

**Comment by shamoya** [comment]
Sounds great, nice design !
I'll complete by end of the week if it's ok

**Comment by yanivbl6** [comment]
thanks, looking forward to testing this.
btw, The results look very promising so far.
I will present it when I can test the cuda benchmark on the 8 hosts X 4 GPUs setup.

**Comment by yanivbl6** [comment]
Note- I have created a new repository and moved most of the files there ( Except for the allreduce implementation). 

https://github.com/yanivbl6/pcx/issues/new
We will use git submodules to add the files to be used by gloo. The algorithm implementation will remain here, for now at least.

**Comment by shamoya** [comment]
Nice work.

**Comment by yanivbl6** [comment]
sorry for being inpatient, I proceeded to integrating your code in PCX.

results:
MEMIC decreases ring algorithm in the 8x4 setting (GPUs) by 3us, which is nice (about 10% for small messages)
For recursive doubling, it seems to speed things up by about 1us.

I conclude that the memic gives a speedup linear to the number of steps (As in theory), so while it is not making a huge difference in our case, it has good potential for improving larger scales collectives.

**Comment by shamoya** [comment]
Very nice, good work.
Sorry for the delay, couldn't get to it.

**Pull request closed without merging**
